### ISSUE TITLE
Could not find configName for collection

### ISSUE THREAD

**Issue by eduardocerqueira** [freedev/solrcloud-zookeeper-docker#1]
Hi @freedev 

I found your repo browsing around about solrcloud and I am very impressive with it! Thank you it has been very helpful. well, I am trying to run my collections from my solr to the volume shared with container by your scripts, for this I copied my collection folder -- see at bottom of this message the folder structure of this folder -- to /home/eduardo/git/solrcloud-zookeeper-docker/solrcloud/data/solr-1/store/solr

After I start the solr using your ./start.sh script solr comes up fine but I can't see the collection and get this error: 

Articles: org.apache.solr.common.cloud.ZooKeeperException:org.apache.solr.common.cloud.ZooKeeperException: Could not find configName for collection Articles found:null

Any idea?

[eduardo@dev solr-articles]$ tree -L 2
.
├── conf
│   ├── admin-extra.html
│   ├── admin-extra.menu-bottom.html
│   ├── admin-extra.menu-top.html
│   ├── currency.xml
│   ├── dataimport.properties
│   ├── db-data-config.xml
│   ├── elevate.xml
│   ├── lang
│   ├── mapping-FoldToASCII.txt
│   ├── mapping-ISOLatin1Accent.txt
│   ├── protwords.txt
│   ├── _rest_managed.json
│   ├── schema.xml
│   ├── solrconfig.xml
│   ├── spellings.txt
│   ├── stopwords.txt
│   ├── synonyms.txt
│   ├── update-script.js
│   └── xslt
├── core.properties
├── data
│   ├── index
│   └── tlog
└── lib
    ├── derby-10.9.1.0.jar
    ├── hsqldb-1.8.0.10.jar
    └── mysql-connector-java-5.1.25-bin.jar

**Comment by freedev** [comment]
I'm sorry but with SolrCloud you cannot copy your collection folder and hope everything works like a charm... The process is a little bit different.

1. copy your `lib/*.jar` files into `/home/eduardo/git/solrcloud-zookeeper-docker/solrcloud/data/solr-1/store/shared-lib`.

2. upload the collection configuration into Zookeeper. 
To upload the configuration just use `zkcli-util.sh`. 
You'll find `zkcli-util.sh` into `/home/eduardo/git/solrcloud-zookeeper-docker`.
After this go into the Solr Admin and have a look at [http://localhost:8081/solr/#/~cloud?view=tree](http://localhost:8081/solr/#/~cloud?view=tree) 
And double check zookeeper `/config/`  folder, there you should see your configuration.

3. Create your collection (may be using [Collections API](https://cwiki.apache.org/confluence/display/solr/Collections+API)).

4. Now can load your documents into the fresh collection. Theoretically, at this point, if your standalone version of Solr is the same of SolrCloud, given you're using the same version of Lucene indexes you could try to brutally copy the index data. But first you have to shutdown SolrCloud. 

Hope this helps.

**Comment by freedev** [comment]
bump :)

**Comment by freedev** [comment]
Given this is not a problem related with the project I'll close the issue, feel free to comment and write me if you need help.
