### ISSUE TITLE
Live deployment example

### ISSUE THREAD

**Issue by si-harps** [freedev/solrcloud-zookeeper-docker#2]
Hi, thanks so much for this superb repo. It's helped me understand how to run SolrCloud with Zookeeper and Docker.

I'm wondering how I can deploy a similar setup to multiple EC2 instances, is there any chance of an example or some pointers on how this could be accomplished? Or, is this out of scope with what you are trying to achieve? Either way, the repo is more than "Star Worthy"! I'd give it 3 if i could! :)

**Comment by freedev** [comment]
Hi @si-harps, to deploy on multiple EC2 instances exist Kubernetes, try with this https://github.com/freedev/solrcloud-zookeeper-kubernetes
