### ISSUE TITLE
new version of solr image continuously restarting

### ISSUE THREAD

**Issue by hwrichter** [freedev/solrcloud-zookeeper-docker#3]
the lates docker image has changed location of log4j.properties
this is causing to restart loops

lines log-config.sh

cp /opt/solr/server/resources/log4j.properties /opt/solr/server/resources/log4j.properties.orig
cp /docker-entrypoint-initdb.d/log4j.properties /opt/solr/server/resources/

failing

**Comment by freedev** [comment]
Hi, thanks for contributing. I've just fixed the problem.

**Comment by freedev** [comment]
The file ```/opt/solr/server/resources/log4j.properties``` has been removed. 
The new log configuration file is ```/opt/solr/server/resources/log4j2.xml``` and finally has rotate log configured by default. So there is no need anymore to fix it.

**Comment by freedev** [comment]
The bug is resolved. Can you test it?
