### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tkokto** [freedev/solrcloud-zookeeper-docker#4]
start-cluster.sh

2019/5/16 下午1:13:40/opt/docker-solr/scripts/solr-foreground: running /docker-entrypoint-initdb.d/log-config.sh
2019/5/16 下午1:13:40mv: cannot stat '/opt/solr/bin/solr.in.sh': No such file or directory

**Comment by freedev** [comment]
@tkokto thanks for reporting this, but unfortunately I'm unable to recreate this problem. Could you please add more information, in order to reproduce this problem?

**Comment by freedev** [comment]
Issue closed because the author hasn't responded to a request for more information.
